### ISSUE TITLE
Runtime.UserCodeSyntaxError in Lambda Function when moving an issue

### ISSUE THREAD

**Issue by Maott** [nileshr/zenalert#10]
Hey @nileshr , 

I tried to set everything up like described in the readme, but it's not working for me.
I don't receive messages in the connected Slack Channel.

The connection between Zenub and the Lamda Function seems to work.
Everytime I move an issue to another pipeline I receive the following error in the AWS log:

`2019-10-17T12:21:37.580Z undefined ERROR Uncaught Exception
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected token u in JSON at position 0",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token u in JSON at position 0",
        "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}`

Do you know anything about this problem?

**Comment by nileshr** [comment]
@Maott Sorry, I seemed to have missed this! Were you able to fix this? Looks to me there was some unexpected error response received from ZenHub.

**Comment by helenana** [comment]
@nileshr Thanks for the Response! Unfortunately the Issue still remains, could it be a problem that we use multiple Zenhub Workspaces?

**Comment by freak3dot** [comment]
Look for a JSON.parse that is parsing an undefined variable.

The `u` at position 0 is actually the `u` in `undefined`.
